name: 🐛 Bug Report
description: Report a bug or issue
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.
        
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is
    validations:
      required: true
      
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Run command '...'
        2. Use parameters '...'
        3. See error
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
      
  - type: textarea
    id: system
    attributes:
      label: System Information
      description: Please provide your system specs
      placeholder: |
        - OS: Ubuntu 22.04
        - Python: 3.10.12
        - GPU: NVIDIA RTX 4090
        - VRAM: 24GB
        - CUDA: 12.1
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Error logs
      description: Paste any error messages or logs
      render: shell
      
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues
          required: true
        - label: I am using the latest version
          required: true
